### ISSUE TITLE
Error  running image with no command

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/scuba#93]
Error:
```
$ scuba --image pyinstaller-fedora25
Traceback (most recent call last):
  File "/usr/bin/scuba", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/scuba/__main__.py", line 402, in main
    rc = run_scuba(scuba_args) or 0
  File "/usr/lib/python2.7/site-packages/scuba/__main__.py", line 370, in run_scuba
    dive.prepare()
  File "/usr/lib/python2.7/site-packages/scuba/__main__.py", line 116, in prepare
    self.__setup_native_run()
  File "/usr/lib/python2.7/site-packages/scuba/__main__.py", line 280, in __setup_native_run
    cmd = entrypoint + cmd
```

Image info:
```
$ docker inspect pyinstaller-fedora25
[
    {
        "Id": "sha256:df23233c6780bbff18a77a68a83e5735f1073dbdd270514e18497fbb8a4fbc29",
        "RepoTags": [
            "pyinstaller-fedora25:latest"
        ],
        "RepoDigests": [],
        "Parent": "sha256:15895ef0b3b2b4e61bf03d38f82b42011ff7f226c681705a4022ae3d1d643888",
        "Comment": "",
        "Created": "2017-05-11T14:03:01.944382774Z",
        "Container": "e1c8b346d58c8275eec297b201d6c5682affed1a59cb6c26bb09abf874cba838",
        "ContainerConfig": {
            "Hostname": "79db519299fc",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DISTTAG=f25docker",
                "FGC=f25",
                "FBR=f25"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "dnf install -y python python-pip \u0026\u0026     pip install pyinstaller"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:15895ef0b3b2b4e61bf03d38f82b42011ff7f226c681705a4022ae3d1d643888",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "1.12.3",
        "Author": "",
        "Config": {
            "Hostname": "79db519299fc",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DISTTAG=f25docker",
                "FGC=f25",
                "FBR=f25"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "sha256:15895ef0b3b2b4e61bf03d38f82b42011ff7f226c681705a4022ae3d1d643888",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 450220300,
        "VirtualSize": 450220300,
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "1679",
                "DeviceName": "docker-253:0-528247-8ef36b2c2a0f1c3e4baa62866d79501b1f701b2b84a2304293584ba9616ae2b3",
                "DeviceSize": "10737418240"
            }
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:53e6d99f7596f656354b326bd771a14ed68f0676f05793a9c3d3b799ae447977",
                "sha256:d8849eaef132e86a11ebe16700f7142a64e29fa2e9007acd55e0a582d6c04ab0"
            ]
        }
    }
]
```

**Comment by JonathonReinhart** [comment]
Duplicate of #103 which was just fixed.
